#!/usr/bin/env python3
"""Regression guards for Android operational P1 contracts."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def fail(message: str) -> None:
    raise SystemExit(f"ANDROID_OPERATIONAL_REGRESSION_FAIL: {message}")


def require(text: str, marker: str, name: str) -> None:
    if marker not in text:
        fail(f"missing {name}: {marker}")


def forbid(text: str, marker: str, name: str) -> None:
    if marker in text:
        fail(f"forbidden {name}: {marker}")


def main() -> None:
    picker = read("android/app/src/main/java/cd/cc/supra/inventory/beta/PickerController.kt")
    reporter = read("android/app/src/main/java/cd/cc/supra/inventory/beta/ReporterController.kt")
    keyed = read("android/app/src/main/java/cd/cc/supra/inventory/beta/KeyedLinearRenderer.kt")
    cache = read("android/app/src/main/java/cd/cc/supra/inventory/beta/SkuCatalogCache.kt")
    main_activity = read("android/app/src/main/java/cd/cc/supra/inventory/beta/MainActivity.kt")
    relay = read("android/app/src/main/java/cd/cc/supra/inventory/beta/RelayPocClient.kt")
    picker_layout = read("android/app/src/main/res/layout/view_picker.xml")
    relay_agent = read("relay-agent/Program.cs")
    relay_agent_config = read("relay-agent/AgentConfig.cs")
    relay_agent_updater = read("relay-agent/AgentUpdater.cs")
    wms_integration = read("relay-agent/WmsIntegration.cs")
    wms_picklist = read("relay-agent/WmsPicklistLookup.cs")
    status_overlay = read("relay-agent/StatusOverlay.cs")
    overlay_settings = read("relay-agent/OverlaySettingsForm.cs")
    agent_leader = read("relay-agent/AgentLeaderCoordinator.cs")
    picklist_cache = read("relay-agent/PicklistCacheCoordinator.cs")
    picker_rate = read("relay-agent/PickerRateLimiter.cs")
    user_startup = read("relay-agent/UserStartupRegistration.cs")
    system_monitor = read("relay-agent/SystemMonitor.cs")
    wms_session_store = read("relay-agent/WmsSessionStore.cs")
    exit_authorization = read("relay-agent/ExitAuthorization.cs")
    runtime_guard = read("relay-agent/AgentRuntimeGuard.cs")
    relay_agent_workflow = read(".github/workflows/verify-relay-agent.yml")
    relay_rules = read("firebase/database.rules.json")
    service_index = read("service/src/index.ts")
    inventory_api = read("android/app/src/main/java/cd/cc/supra/inventory/beta/InventoryApi.kt")
    launcher = read("android/app/src/main/java/cd/cc/supra/inventory/beta/AdminLauncherController.kt")
    manifest = read("android/app/src/main/AndroidManifest.xml")
    gradle = read("android/app/build.gradle.kts")
    verify_apps = read(".github/workflows/verify-apps.yml")
    fcm_service = read("android/app/src/main/java/cd/cc/supra/inventory/beta/StockMessagingService.kt")
    signal_store = read("android/app/src/main/java/cd/cc/supra/inventory/beta/NotificationSignalStore.kt")
    fcm_worker = read("service/src/fcm.ts")
    notifications_core = read("service/src/notifications-core.ts")
    operational = read("service/src/operational-v2-core.ts")
    sla_auto = read("service/src/sla-automation.ts")
    web = read("web/src/operational-app.ts")

    # F09/F11: lifecycle-safe keyed rendering and single-tap withdrawal.
    require(keyed, "class KeyedLinearRenderer", "keyed list renderer")
    require(picker, "historyRenderer", "Picker keyed history")
    require(reporter, "listRenderer", "Reporter keyed list")
    require(picker, "setOnClickListener { confirmWithdraw(row) }", "single-tap withdrawal confirmation")
    forbid(picker, "setOnLongClickListener { confirmWithdraw(row)", "long-press withdrawal")

    # F10: RECEIVED and DISPLAYED are separate; DISPLAYED occurs only after dialog show.
    require(picker, 'api.markResultStage(result.resultEventId, "RECEIVED")', "Picker RECEIVED stage")
    require(picker, "dialog.setOnShowListener", "result visible hook")
    require(picker, 'api.markResultStage(result.resultEventId, "DISPLAYED")', "Picker DISPLAYED stage")
    forbid(picker, 'api.markResultStage(result.resultEventId, "RECEIVED")\n                    api.markResultStage(result.resultEventId, "DISPLAYED")', "eager DISPLAYED after fetch")

    # F13: SQLite staging protects the previous valid catalog.
    require(cache, "SQLiteOpenHelper", "SQLite catalog")
    require(cache, "catalog_stage", "catalog staging table")
    require(cache, "prepareStage(copyCurrent = true)", "delta staging")
    require(cache, "commitStage(info)", "atomic catalog promotion")
    require(cache, "Master SKU thay đổi trong lúc đồng bộ. Cache cũ được giữ nguyên.", "mid-sync authority verification")
    forbid(cache, 'private val cacheFile = File(', "TSV authoritative cache")

    # F12: data-only FCM reaches FirebaseMessagingService and keeps event correlation.
    require(manifest, 'android:name=".StockMessagingService"', "Firebase messaging service manifest")
    require(fcm_service, "class StockMessagingService : FirebaseMessagingService()", "Firebase messaging service")
    require(fcm_service, "NotificationSignalStore.markMessage", "FCM local correlation signal")
    require(signal_store, "pending_result_events", "pending result receipt store")
    require(fcm_worker, "notification_title", "data-only notification title")
    require(fcm_worker, "notification_body", "data-only notification body")
    forbid(fcm_worker, "notification: { title: message.title, body: message.body }", "system notification payload bypassing service")
    require(notifications_core, "notification_delivery_attempts", "delivery attempt persistence")
    require(notifications_core, "/notifications/disable-tokens", "invalid token disable route")
    require(fcm_worker, "UNREGISTERED", "FCM invalid-token classification")
    require(operational, "notification_delivery_attempts", "delivery attempt schema readiness")

    # F21: fail-closed OTA identity and channel verification.
    require(gradle, '"TRUSTED_SIGNER_SHA256"', "trusted signer BuildConfig")
    require(verify_apps, "BETA_SIGNER_SHA256", "release signer derivation")
    require(main_activity, "verifyInstalledSignerTrusted()", "installed signer verification")
    require(main_activity, "verifyDownloadedApk(temp, info)", "downloaded APK identity verification")
    require(main_activity, "archive.packageName != BuildConfig.APPLICATION_ID", "package verification")
    require(main_activity, "archive.longVersionCode != info.versionCode.toLong()", "versionCode verification")
    require(main_activity, 'info.tag != "beta-vc${info.versionCode}"', "Beta channel tag verification")
    require(main_activity, "expectedSigner !in archiveSigners", "downloaded signer verification")
    require(main_activity, "validateUpdateUrl", "trusted update URL verification")
    require(main_activity, "info.versionCode == BuildConfig.VERSION_CODE", "exact latest-version login gate")
    require(main_activity, "info.versionCode < BuildConfig.VERSION_CODE", "unexpected ahead-of-channel fail closed")

    # D060: Android refreshes the server-authoritative effective role on resume.
    require(inventory_api, "fun refreshProfile(): AppSession", "effective-role profile refresh API")
    require(inventory_api, '"/api/auth/me"', "effective-role profile endpoint")
    require(main_activity, "private fun syncEffectiveRole()", "effective-role resume sync")
    require(main_activity, "api.refreshProfile()", "effective-role server refresh")
    require(main_activity, "if (roleChanged || identityChanged || activeSession == null)", "role-change rerender")

    # D075: shared Picker queue + real ADMIN Agent identity + dedicated Agent auto-update.
    require(relay, '.addPathSegment("relay_poc")', "D075 shared relay root")
    require(relay, '.addPathSegment("jobs")', "D075 shared jobs collection")
    forbid(relay, ".addPathSegment(firebaseUid)", "D075 per-Firebase-UID relay branch")
    require(relay, '.put("picker_uid", identity.uid)', "D075 Picker Firebase identity")
    require(relay, '.put("picker_user_id", session.userId)', "D075 Picker application identity")
    require(relay, "agentAdminUserId", "D075 ADMIN ACK identity")
    require(picker_layout, '@+id/panelShortage', "D074/D075 shortage panel")
    require(picker_layout, '@+id/panelConfirmOrder', "D074/D075 confirmation panel")
    require(picker_layout, '@+id/tabShortage', "D074/D075 shortage bottom tab")
    require(picker_layout, '@+id/tabConfirmOrder', "D074/D075 confirmation bottom tab")
    require(picker_layout, 'android:maxLength="5"', "D074/D075 five digit input cap")
    require(picker, "digits.length == 5", "D074/D075 send enabled exactly at five digits")
    require(picker, "result.agentAdminUserId", "D075 Picker shows ADMIN Agent identity")
    require(relay_agent, 'string.Equals(role, "ADMIN"', "D075 Agent effective ADMIN gate")
    require(relay_agent, 'string.Equals(baseRole, "ADMIN"', "D075 Agent immutable base ADMIN gate")
    require(relay_agent, '"agent_admin_user_id"', "D075 Agent ADMIN ACK metadata")
    require(relay_agent, '"agent_instance_id"', "D075 persistent Agent instance metadata")
    require(relay_agent, '"/relay_poc/jobs.json?auth="', "D075 shared Agent collection")
    require(relay_agent, "JobAlreadyAcknowledgedByAnotherAgent", "D075 first-writer ACK ownership")
    require(relay_agent, "LoadOrCreateAgentInstanceId", "D075 persistent Agent instance id")
    require(relay_agent, "ClearStoredSession", "D075 old non-ADMIN session invalidation")
    require(service_index, "app_base_role: user.base_role", "D075 immutable base-role Firebase custom claim")
    require(relay_rules, "auth.token.app_base_role == 'ADMIN'", "D075 real ADMIN RTDB rule")
    require(relay_rules, "newData.child('agent_admin_user_id').val() == auth.token.app_user_id", "D075 ADMIN ACK rule binding")
    require(relay_agent_config, "AgentBuild = 11", "D086 Agent build channel")
    require(relay_agent, "var statusCode = (int)response.StatusCode", "D077 capture HTTP status before dispose")
    require(relay_agent, "ProbeAllTransports", "D078 Test all transport probe")
    require(relay_agent, "AgentConfig.FirestoreProbeUrl", "D078 Firestore probe")
    require(relay_agent, "AgentConfig.AppsScriptWebProbeUrl", "D078 Apps Script web probe")
    require(relay_agent, "AgentConfig.SheetsProbeUrl", "D078 Sheets probe")
    require(relay_agent, "AgentConfig.DriveProbeUrl", "D078 Drive probe")
    require(relay_agent, "LooksLikeCorporateProxyBlock", "D078 corporate proxy classifier")
    require(relay_agent, "PROBE SUMMARY", "D078 compact probe summary")
    require(relay_agent, "OFFICE PROXY BLOCK / RTDB", "D078 RTDB proxy block status")
    require(relay_agent_config, "FirestoreProbeUrl", "D078 Firestore endpoint")
    forbid(relay_agent, "return new RelayHttpException((int)response.StatusCode", "D077 disposed HttpWebResponse StatusCode read")
    require(relay_agent_updater, "CheckAndInstallIfNeeded", "D075 automatic Agent updater")
    require(relay_agent_updater, "Sha256", "D075 Agent SHA-256 verification")
    require(relay_agent_updater, "release-assets.githubusercontent.com", "D075 trusted GitHub CDN update guard")
    require(relay_agent_workflow, "--prerelease", "D075 dedicated Agent prerelease")
    require(relay_agent_workflow, "relay-agent-v$version", "D075 Agent prerelease tag")
    forbid(relay_agent, 'Log("ACK " + suffix', "D075 raw Picklist suffix in Agent log")

    # D080: Agent-owned Edge session capture + strictly read-only Supra connectivity probe.
    require(relay_agent, "CaptureWmsSession", "D080 WMS session capture action")
    require(relay_agent, "TestWmsConnection", "D080 WMS connectivity test action")
    require(wms_integration, "class WmsBrowserCapture", "D080 Agent-owned browser capture")
    require(wms_integration, "--remote-debugging-address=127.0.0.1", "D080 loopback-only DevTools")
    require(wms_integration, 'string.Equals(uri.Host, "api-supra.winmart.vn"', "D080 Supra API capture host allowlist")
    require(wms_integration, '"Authorization", "Token", "APISID", "SID", "SCID", "USID"', "D080 required WMS session headers")
    require(wms_integration, "class WmsReadOnlyClient", "D080 read-only WMS client")
    require(wms_integration, 'request.Method = "GET"', "D080 read-only GET probe")
    require(wms_integration, "HMACSHA256", "D080 per-request Supra signature")
    require(wms_integration, 'const string prefix = "910"', "D080 signature prefix")
    require(relay_agent_config, 'WmsApiProbeSignPath = "/api/v1/warehouse/zones"', "D080 read-only zones probe")
    require(relay_agent_config, 'CorporateProxyFallback = "http://proxyclientdr.winmart.vn:9090"', "D080 corporate proxy fallback")
    require(wms_integration, "session_values=redacted", "D080 WMS session logging redaction")
    forbid(wms_integration, 'request.Method = "POST"', "D080 WMS POST mutation")
    forbid(wms_integration, 'request.Method = "PUT"', "D080 WMS PUT mutation")
    forbid(wms_integration, 'request.Method = "PATCH"', "D080 WMS PATCH mutation")
    forbid(wms_integration, 'request.Method = "DELETE"', "D080 WMS DELETE mutation")

    # D081: login wait reliability, Chromium fallback, password minimization and taskbar monitor.
    require(wms_integration, "FindSupportedBrowser", "D081 supported Chromium discovery")
    require(wms_integration, '"Microsoft Edge"', "D081 Edge primary browser")
    require(wms_integration, '"Google Chrome"', "D081 Chrome fallback browser")
    require(wms_integration, "Receive(socket, remaining)", "D081 whole-login-window WebSocket receive")
    forbid(wms_integration, "TimeSpan.FromSeconds(5) ? TimeSpan.FromSeconds(5)", "D081 per-receive abort timeout")
    require(relay_agent, "WmsBrowserCapture.CaptureSession(300", "D081 five-minute WMS login window")
    require(relay_agent, "_password.Clear();", "D081 clear ADMIN password UI immediately")
    require(relay_agent, "UpdateTrayMonitor", "D081 taskbar monitor updater")
    require(relay_agent, "_trayStatusItem", "D081 taskbar status menu")
    require(system_monitor, "GetSystemTimes", "D081 CPU utilization sampling")
    require(system_monitor, "CallNtPowerInformation", "D081 CPU MHz sampling")
    require(system_monitor, "GlobalMemoryStatusEx", "D081 RAM sampling")
    require(system_monitor, "SUPRA | CPU ", "D081 compact taskbar text")

    # D082: persistent click-through overlay + read-only Picklist existence lookup.
    require(status_overlay, "class StatusOverlayForm", "D082 persistent overlay form")
    require(status_overlay, "HtTransparent", "D082 locked hit-test click-through")
    require(status_overlay, "WsExNoActivate", "D082 locked no-activation overlay")
    require(status_overlay, "TopMost = true", "D082 always-on-top overlay")
    require(status_overlay, "SetOverlayOpacity", "D082 configurable overlay opacity")
    require(status_overlay, "SetLocked", "D082 overlay lock/unlock")
    require(relay_agent, "overlay-settings.json", "D082 overlay persisted settings")
    require(relay_agent, "HasUsableWmsSession", "D082 valid WMS session reuse guard")
    require(relay_agent, '"Phiên Supra đang sẵn sàng"', "D086 block repeated WMS login")
    require(relay_agent, "HandlePicklistLookupJob", "D082 relay Picklist lookup handler")
    require(relay_agent, '"lookup_status"', "D082 lookup result ACK metadata")
    require(wms_picklist, "class WmsPicklistLookupClient", "D082 read-only Picklist lookup client")
    require(wms_picklist, 'request.Method = "GET"', "D082 Picklist lookup GET only")
    require(wms_picklist, 'private const int PageSize = 100', "D084 WMS page size 100")
    require(wms_picklist, '{ "FromDate", "" }', "D084 WMS no FromDate filter")
    require(wms_picklist, '{ "ToDate", "" }', "D084 WMS no ToDate filter")
    require(wms_picklist, '{ "Content", "" }', "D084 WMS empty Content")
    require(wms_picklist, 'string.Equals(field, "PickListCode"', "D084 exact PickListCode field")
    require(wms_picklist, 'text.StartsWith("PL"', "D084 PL code format")
    require(wms_picklist, 'return text.Substring(text.Length - 5, 5)', "D084 trailing five digits from PickListCode")
    require(wms_picklist, 'page * PageSize >= analysis.TotalCount.Value', "D084 all-page pagination")
    forbid(wms_picklist, '"Content", suffix', "D084 server-side suffix Content filter")
    forbid(wms_picklist, "monthStart", "D084 month date filter")
    require(wms_picklist, "TrailingFiveDigits", "D082 exact trailing five digit check")
    require(wms_picklist, '"FOUND"', "D082 found classification")
    require(wms_picklist, '"NOT_FOUND"', "D082 not-found classification")
    require(wms_picklist, '"SCHEMA_UNSUPPORTED"', "D082 unknown-schema fail closed")
    require(relay_agent_config, 'WmsPicklistLookupSignPath = "/api/v1/autopp/pickListConfirms"', "D082 Picklist lookup sign path")
    require(relay_agent_config, 'WmsPicklistConfirmUiReferenceUrl = "https://wms-supra.winmart.vn/sft3/app/saleorder/auto-pickpack-confirm"', "D082 confirm UI reference only")
    require(relay, "lookupStatus", "D082 Android relay lookup status")
    require(picker, '"CÓ PICKLIST"', "D082 PDA found result")
    require(picker, '"KHÔNG CÓ PICKLIST"', "D082 PDA not-found result")
    require(picker_layout, 'android:text="KIỂM TRA PICKLIST"', "D082 read-only lookup action")
    require(relay_rules, '"lookup_status"', "D082 RTDB lookup metadata validation")
    forbid(wms_picklist, 'request.Method = "POST"', "D082 WMS POST mutation")
    forbid(wms_picklist, 'request.Method = "PUT"', "D082 WMS PUT mutation")
    forbid(wms_picklist, 'request.Method = "PATCH"', "D082 WMS PATCH mutation")
    forbid(wms_picklist, 'request.Method = "DELETE"', "D082 WMS DELETE mutation")
    forbid(wms_picklist, "confirmPicklist", "D082 WMS confirm API mutation")
    forbid(relay_agent, "WmsPicklistConfirmUiReferenceUrl)", "D082 confirm UI navigation")

    # D083: Agent v7 startup regression must fail safe instead of silently exiting.
    require(relay_agent, "new AgentForm(startupSmoke, autoStarted)", "D085 startup/autostart mode preserving D083 smoke")
    require(relay_agent, "InitializeStatusOverlaySafe", "D083 lazy overlay init")
    require(relay_agent, '"FATAL startup type="', "D083 top-level startup crash logging")
    require(relay_agent, '"SUPRA Inventory Agent - lỗi khởi động"', "D083 visible fatal startup message")
    require(relay_agent, '"OVERLAY init=FAIL', "D083 overlay failure isolation")
    require(relay_agent_workflow, "--startup-smoke", "D083 CI startup smoke execution")
    require(relay_agent_workflow, "WaitForExit(15000)", "D083 startup smoke timeout")
    forbid(status_overlay, "RecreateHandle()", "D083 no overlay handle recreation during startup")

    # D084: explicit overlay settings + exact all-date PickListCode scan.
    require(relay_agent, '"Cài đặt bảng nổi"', "D084 overlay settings entry")
    require(overlay_settings, "class OverlaySettingsForm", "D084 overlay settings dialog")
    require(overlay_settings, "Độ trong của nền bảng nổi", "D084 overlay opacity setting")
    require(overlay_settings, "Khóa vị trí và cho chuột xuyên qua bảng nổi", "D084 overlay lock setting")
    # D086 keeps the v8 no-recreate behavior but adds a real cross-process click-through style.
    require(status_overlay, "HtTransparent", "D086 locked hit-test fallback")
    require(status_overlay, "WsExTransparent", "D086 true overlay click-through style")
    require(status_overlay, "SetExtendedStyle", "D086 dynamic click-through toggle")
    require(relay_agent, '"Cài đặt bảng nổi"', "D086 settings overlay access")
    require(relay_agent, "TryRestoreWmsSessionFileFirst", "D086 file-first WMS startup")
    require(wms_session_store, "ProtectedData.Protect", "D086 encrypted WMS session file")
    require(wms_session_store, "DataProtectionScope.CurrentUser", "D086 current-user WMS session protection")
    require(exit_authorization, "Rfc2898DeriveBytes", "D086 protected ADMIN exit verifier")
    require(runtime_guard, "--watchdog-restart", "D086 unexpected-exit watchdog")
    require(relay, ".callTimeout(120, TimeUnit.SECONDS)", "D084 all-page relay wait window")
    require(relay, "Quá 2 phút chưa nhận phản hồi tra cứu", "D084 all-page relay timeout copy")

    # D085: sticky single-active Agent, cache/single-flight, persisted anti-spam and no-elevation startup.
    require(agent_leader, "HeartbeatIntervalMs = 3000", "D085 Agent heartbeat")
    require(agent_leader, "FailoverAfterMs = 10000", "D085 Agent failover threshold")
    require(agent_leader, "HttpRequestHeader.IfMatch", "D085 conditional leader election")
    require(picklist_cache, "FreshMissGuardSeconds = 10", "D085 fresh cache miss guard")
    require(picklist_cache, '"JOIN_INFLIGHT"', "D085 single-flight cache refresh")
    require(picker_rate, "StrikeWindowMs = 60L * 1000L", "D085 strike window")
    require(picker_rate, "ResetEscalationAfterMs = 24L * 60L * 60L * 1000L", "D085 escalation reset")
    require(picker_rate, "return 5;", "D085 first lock")
    require(picker_rate, "return 30;", "D085 second lock")
    require(picker_rate, "return 60;", "D085 third/subsequent lock")
    require(user_startup, "Registry.CurrentUser", "D085 normal-user autostart")
    require(user_startup, "CurrentVersion\\Run", "D085 HKCU Run registration")
    require(relay, '"Đang chuyển người xử lý..."', "D085 PDA failover progress")
    require(relay, '"Không có Agent xử lý online. Vui lòng về bàn chuyên viên xử lý trực tiếp."', "D085 no-Agent guidance")
    require(picker, '"PICKER_LOCKED"', "D085 locked Picker state")
    require(picker, "result.rateStrikes", "D085 strike visibility")
    require(relay_rules, '"coordination"', "D085 leader rules")
    require(relay_rules, '"rate_limits"', "D085 rate-limit rules")
    require(relay_rules, "'SWITCHING'", "D085 switching job state")
    require(relay_rules, "'PICKER_LOCKED'", "D085 locked ACK state")

    # F22: launcher actions have distinct targets and Web honors direct hash routes.
    require(launcher, 'openWeb("/#hr"', "HR deep link")
    require(launcher, 'openWeb("/#users"', "users deep link")
    require(launcher, 'openWeb("/#sku"', "SKU deep link")
    require(launcher, 'openWeb("/#sla"', "SLA deep link")

    # D070: Android receives exact timeout state/results without gaining resolve authority.
    require(inventory_api, "autoSkipDeadlineAt", "D070 Picker automatic deadline projection")
    require(inventory_api, "autoSkipAllowedAt", "D070 Picker automatic result projection")
    require(inventory_api, "autoSkipAt", "D070 Reporter next automatic deadline projection")
    require(picker, "Hệ thống tự động do quá hạn", "D070 Picker timeout source copy")
    require(reporter, "Tự động bỏ qua", "D070 Reporter timeout timing copy")
    require(sla_auto, "PER_PICKER", "D070 per-Picker service mode")
    require(sla_auto, "FIRST_REPORT", "D070 first-report service mode")
    require(launcher, "onOpenResults", "distinct results route")
    require(main_activity, 'initialFilter = "HAS_STOCK"', "results initial filter")
    require(web, "sectionFromHash()", "Web hash route parser")
    require(web, "resolveInitialSection", "Web direct-route resolver")
    require(web, "canAccessSection", "Web route RBAC")

    print("ANDROID_OPERATIONAL_REGRESSION_PASS")


if __name__ == "__main__":
    main()
