#!/usr/bin/env python3
"""Regression guards for Android operational P1 contracts."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def fail(message: str) -> None:
    raise SystemExit(f"ANDROID_OPERATIONAL_REGRESSION_FAIL: {message}")


def require(text: str, marker: str, name: str) -> None:
    if marker not in text:
        fail(f"missing {name}: {marker}")


def forbid(text: str, marker: str, name: str) -> None:
    if marker in text:
        fail(f"forbidden {name}: {marker}")


def main() -> None:
    picker = read("android/app/src/main/java/cd/cc/supra/inventory/beta/PickerController.kt")
    reporter = read("android/app/src/main/java/cd/cc/supra/inventory/beta/ReporterController.kt")
    keyed = read("android/app/src/main/java/cd/cc/supra/inventory/beta/KeyedLinearRenderer.kt")
    cache = read("android/app/src/main/java/cd/cc/supra/inventory/beta/SkuCatalogCache.kt")
    main_activity = read("android/app/src/main/java/cd/cc/supra/inventory/beta/MainActivity.kt")
    relay = read("android/app/src/main/java/cd/cc/supra/inventory/beta/RelayPocClient.kt")
    picker_layout = read("android/app/src/main/res/layout/view_picker.xml")
    main_layout = read("android/app/src/main/res/layout/activity_main.xml")
    relay_agent = read("relay-agent/Program.cs")
    relay_agent_config = read("relay-agent/AgentConfig.cs")
    relay_agent_updater = read("relay-agent/AgentUpdater.cs")
    supra_browser = read("relay-agent/SupraConfirmBrowser.cs")
    # D124 supersedes the legacy Windows Agent overlay requirements. Android's
    # CriticalOverlayService remains a separate Picker notification surface.
    if (ROOT / "relay-agent/StatusOverlay.cs").exists():
        fail("D124 Windows Agent StatusOverlay.cs must be removed")
    if (ROOT / "relay-agent/OverlaySettingsForm.cs").exists():
        fail("D124 Windows Agent OverlaySettingsForm.cs must be removed")
    agent_leader = read("relay-agent/AgentLeaderCoordinator.cs")
    picker_rate = read("relay-agent/PickerRateLimiter.cs")
    user_startup = read("relay-agent/UserStartupRegistration.cs")
    system_monitor = read("relay-agent/SystemMonitor.cs")
    exit_authorization = read("relay-agent/ExitAuthorization.cs")
    runtime_guard = read("relay-agent/AgentRuntimeGuard.cs")
    relay_agent_workflow = read(".github/workflows/verify-relay-agent.yml")
    relay_rules = read("firebase/database.rules.json")
    firestore_rules = read("firebase/firestore.rules")
    firestore_transport = read("relay-agent/FirestoreConfirmationTransport.cs")
    firestore_leader = read("relay-agent/FirestoreAgentLeaderCoordinator.cs")
    firestore_rate = read("relay-agent/FirestorePickerRateLimiter.cs")
    confirmation_guard = read("relay-agent/FirestoreConfirmationGuard.cs")
    service_index = read("service/src/index.ts")
    inventory_api = read("android/app/src/main/java/cd/cc/supra/inventory/beta/InventoryApi.kt")
    launcher = read("android/app/src/main/java/cd/cc/supra/inventory/beta/AdminLauncherController.kt")
    manifest = read("android/app/src/main/AndroidManifest.xml")
    gradle = read("android/app/build.gradle.kts")
    verify_apps = read(".github/workflows/verify-apps.yml")
    fcm_service = read("android/app/src/main/java/cd/cc/supra/inventory/beta/StockMessagingService.kt")
    signal_store = read("android/app/src/main/java/cd/cc/supra/inventory/beta/NotificationSignalStore.kt")
    fcm_worker = read("service/src/fcm.ts")
    notifications_core = read("service/src/notifications-core.ts")
    service_core = read("service/src/core.ts")
    read_model = read("service/src/read-model-core.ts")
    firestore_projection = read("service/src/firestore-projection.ts")
    d119_agent = read("relay-agent/D119AgentFeatures.cs")
    picker_presence = read("relay-agent/FirestorePickerPresence.cs")
    operational = read("service/src/operational-v2-core.ts")
    sla_auto = read("service/src/sla-automation.ts")
    web = read("web/src/operational-app.ts")

    # F09/F11 + D110: Picker keeps keyed history; Reporter uses bounded XML ListView adapters with per-batch mutation locking.
    require(keyed, "class KeyedLinearRenderer", "keyed list renderer")
    require(picker, "historyRenderer", "Picker keyed history")
    require(reporter, "private fun pendingAdapter", "D110 Reporter pending adapter")
    require(reporter, "private fun recentAdapter", "D110 Reporter recent adapter")
    require(reporter, "processingBatchIds", "D110 Reporter per-batch mutation lock")
    require(picker, "setOnClickListener { confirmWithdraw(row) }", "single-tap withdrawal confirmation")
    forbid(picker, "setOnLongClickListener { confirmWithdraw(row)", "long-press withdrawal")

    # F10: RECEIVED and DISPLAYED are separate; DISPLAYED occurs only after dialog show.
    require(picker, 'api.markResultStage(result.resultEventId, "RECEIVED")', "Picker RECEIVED stage")
    require(picker, "dialog.setOnShowListener", "result visible hook")
    require(picker, 'api.markResultStage(result.resultEventId, "DISPLAYED")', "Picker DISPLAYED stage")
    forbid(picker, 'api.markResultStage(result.resultEventId, "RECEIVED")\n                    api.markResultStage(result.resultEventId, "DISPLAYED")', "eager DISPLAYED after fetch")

    # F13: SQLite staging protects the previous valid catalog.
    require(cache, "SQLiteOpenHelper", "SQLite catalog")
    require(cache, "catalog_stage", "catalog staging table")
    require(cache, "prepareStage(copyCurrent = true)", "delta staging")
    require(cache, "commitStage(info)", "atomic catalog promotion")
    require(cache, "Master SKU thay đổi trong lúc đồng bộ. Cache cũ được giữ nguyên.", "mid-sync authority verification")
    forbid(cache, 'private val cacheFile = File(', "TSV authoritative cache")

    # F12: data-only FCM reaches FirebaseMessagingService and keeps event correlation.
    require(manifest, 'android:name=".StockMessagingService"', "Firebase messaging service manifest")
    require(fcm_service, "class StockMessagingService : FirebaseMessagingService()", "Firebase messaging service")
    require(fcm_service, "NotificationSignalStore.markMessage", "FCM local correlation signal")
    require(signal_store, "pending_result_events", "pending result receipt store")
    require(signal_store, "overlay_presented_results", "D120 cross-app result overlay ownership")
    require(signal_store, "overlay_ack_pending", "D120 durable overlay acknowledgement retry")
    require(main_activity, "renderSessionRestoring", "D120 session restore without login flash")
    require(main_activity, "drainOverlayAcknowledgements", "D120 overlay acknowledgement recovery")
    require(picker, "isResultOverlayPresented", "D120 duplicate in-app result suppression")
    require(fcm_service, "CriticalOverlayService.MODE_RESULT", "D120 single cross-app result surface")
    require(fcm_worker, "notification_title", "data-only notification title")
    require(fcm_worker, "notification_body", "data-only notification body")
    forbid(fcm_worker, "notification: { title: message.title, body: message.body }", "system notification payload bypassing service")
    require(notifications_core, "notification_delivery_attempts", "delivery attempt persistence")
    require(notifications_core, "/notifications/disable-tokens", "invalid token disable route")
    require(notifications_core, 'state.getWebSockets("role:PICKER")', "D120 active Picker socket authority")
    require(notifications_core, 'attachment.client_type !== "ANDROID"', "D120 Android-only Picker online filter")
    require(firestore_projection, "schema_version: 3", "D127 Picker presence projection schema v3")
    require(firestore_projection, 'presence_source: "ACTIVE_ANDROID_EVENT_DRIVEN"', "D127 Picker presence projection source marker")
    require(read_model, "onPickerAndroidPresenceChanged", "D120 Picker socket-connect projection refresh")
    require(service_core, "webSocketClose", "D120 Picker socket-close projection refresh")
    require(service_core, "syncPickerPresenceProjectionFromState", "D120 direct live Picker projection refresh")
    require(d119_agent, "SmoothDataGridView", "D120 double-buffered Picker grid")
    require(d119_agent, "_pickerOnlineRenderSignature", "D120 no-op Picker render suppression")
    forbid(d119_agent, "if (authenticated && authChanged) RefreshD119OperationalViews(true);", "D120 authenticated list-clear flicker branch")
    require(picker_presence, "schemaVersion != 3", "D127 legacy Picker projection rejection")
    require(picker_presence, "ACTIVE_ANDROID_EVENT_DRIVEN", "D127 event-driven Picker projection source enforcement")
    require(fcm_worker, "UNREGISTERED", "FCM invalid-token classification")
    require(operational, "notification_delivery_attempts", "delivery attempt schema readiness")

    # F21: fail-closed OTA identity and channel verification.
    require(gradle, '"TRUSTED_SIGNER_SHA256"', "trusted signer BuildConfig")
    require(verify_apps, "BETA_SIGNER_SHA256", "release signer derivation")
    require(main_activity, "verifyInstalledSignerTrusted()", "installed signer verification")
    require(main_activity, "verifyDownloadedApk(temp, info)", "downloaded APK identity verification")
    require(main_activity, "archive.packageName != BuildConfig.APPLICATION_ID", "package verification")
    require(main_activity, "archive.longVersionCode != info.versionCode.toLong()", "versionCode verification")
    require(main_activity, 'info.tag != "beta-vc${info.versionCode}"', "Beta channel tag verification")
    require(main_activity, "expectedSigner !in archiveSigners", "downloaded signer verification")
    require(main_activity, "validateUpdateUrl", "trusted update URL verification")
    require(main_activity, "info.versionCode == BuildConfig.VERSION_CODE", "exact latest-version login gate")
    require(main_activity, "info.versionCode < BuildConfig.VERSION_CODE", "unexpected ahead-of-channel fail closed")

    # D060: Android refreshes the server-authoritative effective role on resume.
    require(inventory_api, "fun refreshProfile(): AppSession", "effective-role profile refresh API")
    require(inventory_api, '"/api/auth/me"', "effective-role profile endpoint")
    require(main_activity, "private fun syncEffectiveRole()", "effective-role resume sync")
    require(main_activity, "api.refreshProfile()", "effective-role server refresh")
    require(main_activity, "if (roleChanged || identityChanged || activeSession == null)", "role-change rerender")

    # D097: authenticated Firestore listener + quota-safe PRIMARY/STANDBY/FROZEN carrier.
    require(gradle, 'implementation("com.google.firebase:firebase-auth")', "D097 Firebase Auth SDK")
    require(gradle, 'implementation("com.google.firebase:firebase-firestore")', "D097 Firestore SDK")
    require(relay, "ANDROID_CONFIRM_V1", "D097 Firestore confirmation request source")
    require(relay, "addSnapshotListener", "D097 one-document realtime listener")
    require(relay, "setPersistenceEnabled(false)", "D097 no offline Firestore business queue")
    require(relay, '"created_at" to FieldValue.serverTimestamp()', "D097 server timestamp request age")
    require(relay, "TOTAL_WAIT_MS = 20_000L", "D117 20-second terminal wait")
    require(relay, "FAILOVER_NOTICE_MS = 10_000L", "D097 10-second standby notice")
    require(inventory_api, "relayCustomToken", "D097 bounded Android Firebase listener token")
    require(service_index, "firebase_custom_token", "D097 service returns Android relay token")
    forbid(relay, "FIREBASE_RTDB_URL", "D097 Android RTDB fallback")
    require(relay, "agentAdminUserId", "D097 ADMIN ACK identity")
    require(firestore_rules, "relay_poc_jobs", "D097 Firestore relay collection Rules")
    require(firestore_rules, "request.auth.token.app_base_role == 'ADMIN'", "D097 real ADMIN Firestore rule")
    require(firestore_rules, "resource.data.status == 'PENDING'", "D097 direct ACK source state")
    require(firestore_rules, "request.resource.data.status == 'ACK'", "D097 direct ACK destination state")
    forbid(firestore_rules, "status == 'PROCESSING'", "D097 no PROCESSING state")
    require(firestore_transport, "PrimaryIdlePollIntervalMs = 4000", "D117 PRIMARY 4-second idle polling")
    require(firestore_transport, "PrimaryHotPollIntervalMs = 2000", "D117 PRIMARY 2-second hot polling")
    require(firestore_transport, "StandbyPollIntervalMs = 0", "D117 STANDBY zero business polling")
    require(firestore_transport, "MaxConcurrentJobs = 12", "D097 bounded 30-user concurrency")
    require(firestore_transport, "CONFIRM_ACK_VERIFY", "D115 ACK server verification")
    require(firestore_transport, "ACK RECOVERED", "D115 ACK recovery telemetry")
    require(relay, "triggerCleanupAsync", "D115 Android background cleanup")
    require(relay, "Source.SERVER", "D115 Android final server ACK read")
    forbid(firestore_transport, '"PROCESSING"', "D097 no per-job claim write")
    require(picker_layout, '@+id/panelShortage', "D074/D075 shortage panel")
    require(picker_layout, '@+id/panelConfirmOrder', "D074/D075 confirmation panel")
    require(picker_layout, '@+id/tabShortage', "D074/D075 shortage bottom tab")
    require(picker_layout, '@+id/tabConfirmOrder', "D074/D075 confirmation bottom tab")
    require(picker_layout, 'android:maxLength="20"', "D114 3-20 digit Picker input cap")
    require(picker, "digits.length < 3", "D114 Picker minimum three-digit readiness")
    require(picker, "suppressRelayInputHint", "D116 terminal relay result survives input reset")
    require(picker, "result.agentAdminUserId", "D075 Picker shows ADMIN Agent identity")
    require(relay_agent, 'string.Equals(role, "ADMIN"', "D075 Agent effective ADMIN gate")
    require(relay_agent, 'string.Equals(baseRole, "ADMIN"', "D075 Agent immutable base ADMIN gate")
    require(firestore_transport, '"agent_admin_user_id"', "D126 retained Firestore Agent ACK actor metadata")
    require(firestore_transport, '"agent_instance_id"', "D126 retained Firestore Agent instance metadata")
    require(firestore_transport, 'status", StringField("ACK")', "D126 direct Firestore terminal ACK")
    require(firestore_transport, "AckAlreadyVisible", "D126 ACK recovery/first-writer visibility")
    require(relay_agent, "LoadOrCreateAgentInstanceId", "D126 persistent Agent instance id")
    require(relay_agent, "ClearStoredSession", "D126 invalid Agent session cleanup")
    require(service_index, "app_base_role: user.base_role", "D126 immutable base-role Firebase custom claim")
    require(firestore_rules, "function isAgentOperator()", "D126 Firestore Agent operator rule")
    require(firestore_rules, "request.resource.data.agent_admin_user_id == request.auth.token.app_user_id", "D126 Firestore ACK actor binding")
    require(firestore_rules, "request.auth.token.app_role == 'PICKPACK_ADMIN'", "D119/D126 PickPack Admin Agent authority retained")
    require(relay_agent_config, "AgentBuild = 57", "D127 v57 Agent build channel")
    require(relay_agent, "QueueNetworkStatusRefresh", "D122 SSID refresh off WinForms UI thread")
    require(relay_agent, "QueueWatchdogRefresh", "D122 watchdog refresh off WinForms UI thread")
    require(relay_agent, "ExpireAgentSession", "D122 expired Agent session login recovery")
    require(relay_agent, "var statusCode = (int)response.StatusCode", "D077 capture HTTP status before dispose")
    require(relay_agent, "ProbeAllTransports", "D078 Test all transport probe")
    require(relay_agent, "AgentConfig.FirestoreProbeUrl", "D078 Firestore probe")
    require(relay_agent, "AgentConfig.AppsScriptWebProbeUrl", "D078 Apps Script web probe")
    require(relay_agent, "AgentConfig.SheetsProbeUrl", "D078 Sheets probe")
    require(relay_agent, "AgentConfig.DriveProbeUrl", "D078 Drive probe")
    require(relay_agent, "LooksLikeCorporateProxyBlock", "D078 corporate proxy classifier")
    require(relay_agent, "PROBE SUMMARY", "D078 compact probe summary")
    require(relay_agent, "OFFICE PROXY BLOCK / Firestore", "D126 Office Firestore proxy block status")
    require(relay_agent_config, "FirestoreProbeUrl", "D078 Firestore endpoint")
    forbid(relay_agent, "return new RelayHttpException((int)response.StatusCode", "D077 disposed HttpWebResponse StatusCode read")
    require(relay_agent_updater, "CheckAndInstallIfNeeded", "D075 automatic Agent updater")
    require(relay_agent_updater, "Sha256", "D075 Agent SHA-256 verification")
    require(relay_agent_updater, "release-assets.githubusercontent.com", "D075 trusted GitHub CDN update guard")
    require(relay_agent_workflow, "--prerelease", "D075 dedicated Agent prerelease")
    require(relay_agent_workflow, "relay-agent-v$version", "D075 Agent prerelease tag")
    forbid(relay_agent, 'Log("ACK " + suffix', "D075 raw Picklist suffix in Agent log")

    # D126 supersedes the old captured-session/direct-WMS adapter while preserving
    # the released Android confirmation transport, Agent HA, rate limits and guards.
    require(relay_agent_config,
            'WmsPicklistConfirmUiReferenceUrl = "https://wms-supra.winmart.vn/sft3/app/saleorder/auto-pickpack-confirm"',
            "D126 managed browser Confirm PickList page")
    require(supra_browser, "class SupraConfirmBrowser", "D126 managed browser adapter")
    require(supra_browser, "--remote-debugging-address=127.0.0.1", "D126 loopback-only DevTools")
    require(supra_browser, '"Microsoft Edge"', "D126 Edge support")
    require(supra_browser, '"Google Chrome"', "D126 Chrome support")
    require(supra_browser, 'CommandNoLock("Runtime.enable"', "D126 Runtime DOM access")
    require(supra_browser, 'CommandNoLock("Page.enable"', "D126 Page DOM lifecycle")
    require(supra_browser, 'private const string SearchText = "Tìm kiếm"', "D126 exact search control")
    require(supra_browser, 'private const string ConfirmText = "Xác nhận lấy lại hàng"', "D126 exact confirm control")
    require(supra_browser, 'Regex.IsMatch(code, "^PL[0-9]+$")', "D126 exact PL+digits code")
    require(supra_browser, "code.endsWith(term)", "D126 exact numeric suffix match")
    require(supra_browser, "ClickExactButtonNoLock(SearchText)", "D126 one semantic search retry")
    require(supra_browser, "ROW_AMBIGUOUS", "D126 ambiguous row fail closed")
    require(supra_browser, "CHECKBOX_NOT_UNIQUE", "D126 row checkbox uniqueness guard")
    require(supra_browser, "CHECKBOX_VERIFY_FAILED", "D126 checkbox checked-state guard")
    require(supra_browser, "CONFIRM_BUTTON_NOT_UNIQUE", "D126 exact confirm-button uniqueness guard")
    require(supra_browser, "CONFIRM_IN_PROGRESS_OR_UNCERTAIN", "D126 uncertain terminal state fail closed")
    require(supra_browser, "SW_HIDE", "D126 browser hide support")
    require(supra_browser, "SW_RESTORE", "D126 browser restore support")
    require(supra_browser, "CONFIRM_DOM_PARTIAL", "D126 hotfix partial DOM state")
    require(supra_browser, "[role=grid]", "D126 hotfix grid readiness")
    require(supra_browser, "tr,[role=row]", "D126 hotfix semantic row scan")
    require(supra_browser, "a,[role=button]", "D126 hotfix semantic action scan")
    require(supra_browser, "ConfirmVisibleCount", "D126 hotfix browser diagnostics")
    require(supra_browser, "await new Promise", "D126 hotfix bounded UI settle wait")
    require(supra_browser, "TryReconnectNoLock", "D126 H2 DevTools reconnect")
    require(supra_browser, "StopManagedBrowserNoLock", "D126 H2 managed-browser restart recovery")
    require(supra_browser, "getAttribute('aria-label')", "D126 H2 search aria-label recognition")
    require(supra_browser, "getAttribute('title')", "D126 H2 search title recognition")
    require(supra_browser, "querySelectorAll('body *')", "D126 H2 exact-text leaf search fallback")
    require(supra_browser, "decorationOnly", "D126 H3 decorative search-label sanitizer")
    require(supra_browser, "searchDecoratedCount", "D126 H3 decorated search diagnostics")
    require(supra_browser, "search|magnify|magnifying|glass|find|icon", "D126 H3 icon-label tokens")
    require(supra_browser, "names(e).some(v => fold(v) === fold('Xác nhận lấy lại hàng'))", "D126 H3 readiness confirm stays exact")
    require(supra_browser, 'private const string ConfirmDialogTitle = "XÁC NHẬN LẤY LẠI HÀNG"', "D126 H4 exact confirmation dialog title")
    require(supra_browser, 'private const string ConfirmDialogBody = "Bạn có chắc chắn cho phép lấy hàng lại không?"', "D126 H4 exact confirmation dialog body")
    require(supra_browser, 'private const string ConfirmDialogButtonText = "Xác nhận"', "D126 H4 exact modal confirm action")
    require(supra_browser, 'private const string ConfirmDialogCloseText = "Đóng"', "D126 H4 dialog shape close action")
    require(supra_browser, "CONFIRM_DIALOG_NOT_FOUND", "D126 H4 modal required fail closed")
    require(supra_browser, "CONFIRM_DIALOG_AMBIGUOUS", "D126 H4 modal ambiguity fail closed")
    require(supra_browser, "CONFIRM_DIALOG_BUTTON_NOT_UNIQUE", "D126 H4 modal confirm uniqueness")
    require(supra_browser, "CONFIRM_DIALOG_CLOSE_NOT_UNIQUE", "D126 H4 modal shape guard")
    require(supra_browser, "stage:'DIALOG_CONFIRMED'", "D126 H4 modal confirmation terminal pre-post stage")
    forbid(supra_browser, "dialogClose[0].click", "D126 H4 never activates modal close action")

    forbid(supra_browser, "Network.enable", "D126 no browser network inspection")
    forbid(supra_browser, "Network.requestWillBeSent", "D126 no request/session capture")
    forbid(supra_browser, "document.cookie", "D126 no cookie extraction")
    forbid(supra_browser, "api-supra.winmart.vn", "D126 no direct WMS API host")
    forbid(supra_browser, "confirmSkipItem", "D126 no direct WMS mutation endpoint")
    forbid(supra_browser, "APISID", "D126 no WMS session header extraction")
    forbid(supra_browser, "X-Signature", "D126 no WMS signing material")
    forbid(supra_browser, "SetCursorPos", "D126 no coordinate mutation fallback")
    forbid(supra_browser, "SendKeys.Send", "D126 no keyboard-coordinate automation")

    for retired in [
        "relay-agent/WmsIntegration.cs",
        "relay-agent/WmsSessionStore.cs",
        "relay-agent/WmsPicklistLookup.cs",
        "relay-agent/WmsPicklistExactResolver.cs",
        "relay-agent/WmsPicklistConfirm.cs",
        "relay-agent/WmsSkuCatalog.cs",
        "relay-agent/PicklistCacheCoordinator.cs",
        "relay-agent/FirestoreSkuSync.cs",
    ]:
        if (ROOT / retired).exists():
            fail(f"D126 retired WMS/SKU source still present: {retired}")

    forbid(relay_agent_config, "api-supra.winmart.vn", "D126 direct WMS API config")
    forbid(relay_agent_config, "confirmSkipItem", "D126 direct WMS confirmation config")
    forbid(relay_agent_config, "binStocks", "D126 WMS SKU catalog config")
    forbid(relay_agent_config, "sku_sync_jobs", "D126 Agent SKU staging config")

    require(relay_agent, "Mở trình duyệt Agent", "D127 explicit Agent browser open action")
    require(relay_agent, "Mở trình duyệt Desktop", "D127 explicit Desktop browser open action")
    require(relay_agent, "Web Confirm sẵn sàng", "D126 browser ready state")
    require(relay_agent, "OpenSupraConfirmBrowser", "D126 browser open wiring")
    require(relay_agent, "ToggleSupraBrowserVisibility", "D126 hide/show wiring")
    require(relay_agent, "HasReadyConfirmBrowser", "D126 readiness gate")
    require(relay_agent, "SearchManualPicklists", "D126 manual PickList search")
    require(relay_agent, "ConfirmManualPicklist", "D126 manual confirmation action")
    require(relay_agent, "ProcessFirestoreConfirmations", "D126 PDA batch handler")
    require(relay_agent, "adapter=BROWSER_DOM", "D126 browser adapter audit")
    require(relay_agent, "FINAL_20S_FENCE", "D126 preserved final request-age fence")
    require(relay_agent, "ROLE_GENERATION_FENCE", "D126 preserved generation fence")
    require(relay_agent, "VerifyPrimaryBeforeMutation(appSession)", "D126 pre-mutation PRIMARY fence")
    require(relay_agent, "ProbeSupraBrowserForTakeover", "D126 takeover browser-readiness probe")
    forbid(relay_agent, "CaptureWmsSession", "D126 removed WMS session capture")
    forbid(relay_agent, "TryRestoreWmsSessionFileFirst", "D126 removed WMS session file restore")
    forbid(relay_agent, "WmsSessionStore", "D126 removed DPAPI WMS session")
    forbid(relay_agent, "WmsPicklistConfirmClient", "D126 removed direct WMS confirmation")
    forbid(relay_agent, "WmsPicklistLookupClient", "D126 removed direct WMS lookup")
    forbid(relay_agent, "WmsExactPicklistResolver", "D126 removed direct exact resolver")
    forbid(relay_agent, "WmsSkuCatalogClient", "D126 removed WMS SKU catalog")
    forbid(relay_agent, "RunSkuSync(", "D126 removed Agent SKU sync action")
    forbid(d119_agent, "RunSkuSync", "D126 Agent SKU manual/automatic sync retired")
    forbid(d119_agent, "FirestoreSkuSyncClient", "D126 Firestore SKU client retired")
    forbid(d119_agent, "WmsSkuCatalogClient", "D126 WMS SKU reader retired")
    require(firestore_rules, "match /sku_sync_jobs/{jobId}", "D126 historical SKU staging rule retained")
    require(firestore_rules, "allow read, write: if false;", "D126 SKU staging deny-all")

    # Existing Android/PDA confirmation UX and Firestore transport remain active.
    require(relay, "lookupStatus", "D126 Android confirmation result status")
    require(picker, '"CONFIRMED"', "D126 confirmed result mapping")
    require(picker, '"NOT_FOUND"', "D126 not-found result mapping")
    require(picker, "Đã xác nhận PickList thành công. Quay lại SFT / SFT 3 để tiếp tục.", "D126 Picker success copy")
    require(picker_layout, 'android:text="XÁC NHẬN LẤY LẠI ĐƠN"', "D126 Android confirmation action")
    require(picker, "relayPocClient.sendProbe(suffix)", "D126 Android uses dedicated Firestore relay")
    require(picker, "relayRequestInFlight", "D126 Android in-flight action gate")
    require(picker, '"PICKER_LOCKED"', "D126 Android anti-spam locked state")
    require(picker, "result.rateStrikes", "D126 Android strike visibility")
    require(picker, "renderRelayCandidates", "D126 Android ambiguous candidates")
    require(picker, "confirmAmbiguousPickList", "D126 Android explicit ambiguous candidate selection")
    require(picker, '.setNegativeButton("Huỷ", null)', "D126 ambiguous-selection cancel")
    require(picker, 'Không tìm thấy PickList khớp đúng các số cuối', "D126 precise not-found copy")
    forbid(picker_layout, 'android:hint="5 số cuối Picklist"', "D126 no forced five-digit hint")
    forbid(picker, "digits.length == 5", "D126 no forced five-digit readiness")
    require(relay, 'Regex("^\\\\d{3,20}$")', "D126 Android 3-20 digit suffix request")
    require(relay, "candidatePicklists", "D126 Android receives bounded ambiguous candidates")
    forbid(relay, "/api/picker/reports", "D126 confirmation does not use Báo hàng mutation API")

    # Firestore queue / HA / rate / idempotency remain protected from D117/D118.
    require(firestore_transport, "ProcessBatch", "D126 bounded Firestore logical batch")
    require(firestore_transport, "as IEnumerable", "D126 Firestore JSON-array parsing")
    forbid(firestore_transport, "DeserializeObject(raw) as ArrayList", "D126 no broken Firestore array cast")
    forbid(firestore_transport, "docsObj as ArrayList", "D126 no broken listDocuments array cast")
    require(firestore_transport, "value.Length < 3 || value.Length > 20", "D126 transport suffix guard")
    require(firestore_transport, "picklist_suffix=redacted", "D126 redacted suffix audit")
    require(firestore_transport, "candidate_picklists", "D126 bounded candidate ACK field")
    require(firestore_leader, "FailoverAfterMs = 10000", "D126 10-second failover")
    require(firestore_leader, "PrimaryLeaseHeartbeatMs = 7000", "D126 primary lease heartbeat")
    require(firestore_leader, "PresenceHeartbeatIntervalMs = 900000", "D126 bounded Agent presence")
    require(firestore_leader, "FROZEN", "D126 frozen role")
    require(firestore_leader, "StandbyRoleRefreshMs = 60000", "D126 standby convergence")
    require(firestore_leader, "FrozenRoleRefreshMs = 30000", "D126 frozen convergence")
    require(firestore_leader, "VerifyPrimaryBeforeMutation", "D126 generation mutation fence")
    require(firestore_leader, "PublishScheduleDecision", "D126 shared schedule decision")
    require(firestore_leader, "PublishEarlyStartAndClaimPrimary", "D126 early-start authority")
    require(firestore_leader, "ANY_AUTHENTICATED_AGENT", "D126 any Agent overtime decision")
    require(firestore_leader, "currentDocument.updateTime", "D126 Firestore CAS")
    require(firestore_rate, "StrikeWindowMs = 60L * 1000L", "D126 Firestore strike window")
    require(firestore_rate, "last_request_id", "D126 persisted wrong-input idempotency")
    require(firestore_rate, "ClearFound", "D126 found clears wrong-input state")
    require(firestore_rate, "return 5;", "D126 first lock")
    require(firestore_rate, "return 30;", "D126 second lock")
    require(firestore_rate, "return 60;", "D126 third lock")
    require(confirmation_guard, "relay_poc_confirm_guards", "D126 cross-Agent idempotency guard")
    require(confirmation_guard, "OriginalJobProvesConfirmed", "D126 one-write confirmation proof")
    require(confirmation_guard, "MarkLocalConfirmed", "D126 local confirmed state")
    forbid(confirmation_guard, "MarkConfirmed(", "D126 no second guard-confirm write")
    require(firestore_rules, "^[0-9]{3,20}$", "D126 Firestore suffix rule")
    require(firestore_rules, "relay_poc_rate_limits", "D126 rate-limit rules")
    require(firestore_rules, "relay_poc_coordination", "D126 leader rules")
    require(firestore_rules, "relay_poc_confirm_guards", "D126 confirmation guard rules")

    # Existing Agent lifecycle, diagnostics and operator UI remain.
    require(relay_agent, "_password.Clear();", "D126 clear Agent password UI immediately")
    require(relay_agent, "UpdateTrayMonitor", "D126 taskbar monitor updater")
    require(relay_agent, "_trayStatusItem", "D126 taskbar status menu")
    require(system_monitor, "GetSystemTimes", "D126 CPU utilization sampling")
    require(system_monitor, "CallNtPowerInformation", "D126 CPU MHz sampling")
    require(system_monitor, "GlobalMemoryStatusEx", "D126 RAM sampling")
    require(system_monitor, "SUPRA | CPU ", "D126 compact taskbar text")
    require(relay_agent, "new AgentForm(startupSmoke, autoStarted, activateEvent)", "D126 startup smoke wiring")
    require(relay_agent, '"FATAL startup type="', "D126 top-level startup crash logging")
    require(relay_agent, '"Agent Auto Confirm Pick Pack - lỗi khởi động"', "D126 visible startup failure")
    require(relay_agent_workflow, "--startup-smoke", "D126 CI startup smoke")
    require(relay_agent_workflow, "WaitForExit(15000)", "D126 startup smoke timeout")
    require(exit_authorization, "Rfc2898DeriveBytes", "D126 protected Agent exit verifier")
    require(runtime_guard, "--watchdog-restart", "D126 unexpected-exit watchdog")
    require(relay_agent, "WriteAudit", "D126 split PDA-Agent audit")
    require(firestore_transport, "picklist_suffix=redacted", "D126 operational suffix audit stays redacted")
    require(user_startup, "Registry.CurrentUser", "D126 normal-user autostart")
    require(user_startup, "CurrentVersion\\Run", "D126 HKCU Run registration")
    require(relay_agent, "NetworkChange.NetworkAddressChanged", "D126 network-change proxy refresh")
    require(relay_agent, "FirestoreHttpTransport.NotifyNetworkChange()", "D126 network transition marker")
    require(relay_agent, "15000", "D126 staged Windows proxy refresh")
    require(relay_agent, 'new TabPage("Tổng quan")', "D126 single Overview tab")
    forbid(relay_agent, 'new TabPage("Hệ thống Supra")', "D126 no split Supra tab")
    forbid(relay_agent, 'new TabPage("Xử lý PickList")', "D126 no split PickList tab")
    require(relay_agent, '"Kiểm tra cập nhật"', "D126 manual Agent update")
    require(relay_agent, "WindowState = FormWindowState.Maximized", "D126 maximized Agent window")
    require(relay_agent, "MaximizedBounds = screen.WorkingArea", "D126 taskbar-safe maximized bounds")
    require(relay_agent, "TryParseManualPicklistQueries", "D126 manual comma multi-search")
    require(relay_agent, "ConfirmAllManualPicklists", "D126 manual confirm-all action")
    require(relay_agent, "_manualPicklistConfirmAll.Visible = count >= 2", "D126 confirm-all visibility")
    require(relay_agent, "_manualPicklistOperationRunning", "D126 manual single-flight gate")
    require(relay_agent, 'Name = "ConfirmStatus"', "D126 per-PickList result status")
    require(relay_agent, 'Name = "ConfirmAction"', "D126 per-row confirm action")
    require(relay_agent, 'Text = "Xác nhận"', "D126 row confirm label")
    require(relay_agent, "CheckAfterHoursSchedule", "D126 after-hours prompt loop")
    require(relay_agent, "StartRelayBeforeSix", "D126 early-start relay control")
    require(relay_agent, "Phát triển hệ thống · tamnv2 | Pick Pack 1291", "D126 Agent footer")
    require(relay_agent, "TotalMinutes < 5", "D126 five-minute reminder")
    require(firestore_transport, "_businessEnabled()", "D126 scheduled relay business gate")

    # D088: unified naming/icon, persistent Android session, tray-only Agent and editable overlay.
    require(main_activity, '"1291 Beta"', "D088 Android product name")
    require(inventory_api, '.put("client_type", "ANDROID")', "D088 Android session channel")
    require(main_activity, "restoreInteractiveSession", "D088 Android persistent session restore")
    require(main_activity, "persistInteractiveSession", "D088 Android persistent session save")
    require(relay_agent, "Agent Auto Confirm Pick Pack", "D088 Agent product name")
    require(relay_agent, "identitytoolkit.googleapis.com/v1/accounts:signInWithPassword", "D098 direct Firebase Agent auth channel")
    require(relay_agent, "FirestoreAgentSessionGate", "D098 independent Agent session slot")
    require(relay_agent, "MinimizeToTray", "D088 Agent tray-only minimize")
    require(relay_agent, "ShowInTaskbar = false", "D088 hidden taskbar while minimized")
    require(relay_agent_config, 'AgentExeAsset = "Agent.Auto.Confirm.Pick.Pack.exe"', "D088 canonical Agent asset name")
    require(manifest, 'android:icon="@drawable/app_icon_d089"', "D089 approved Android icon")
    require(manifest, 'android:roundIcon="@drawable/app_icon_d089"', "D089 approved Android round icon")
    require(relay_agent, "MainInstanceMutexName", "D089 Agent single-instance mutex")
    require(relay_agent, "EventWaitHandle.OpenExisting", "D089 duplicate launch activates existing Agent")

    # F22: launcher actions have distinct targets and Web honors direct hash routes.
    require(launcher, 'openWeb("/#hr"', "HR deep link")
    require(launcher, 'openWeb("/#users"', "users deep link")
    require(launcher, 'openWeb("/#sku"', "SKU deep link")
    require(launcher, 'openWeb("/#sla"', "SLA deep link")

    # D070: Android receives exact timeout state/results without gaining resolve authority.
    require(inventory_api, "autoSkipDeadlineAt", "D070 Picker automatic deadline projection")
    require(inventory_api, "autoSkipAllowedAt", "D070 Picker automatic result projection")
    require(inventory_api, "autoSkipAt", "D070 Reporter next automatic deadline projection")
    if "Hệ thống tự động do quá hạn" not in picker and "Hệ thống tự động lúc:" not in picker:
        fail("missing D070/D109 Picker timeout source copy")
    require(reporter, "private fun liveTiming", "D110 Reporter local SLA timing")
    require(reporter, "scheduleMinuteTicker", "D110 Reporter minute ticker")
    require(sla_auto, "PER_PICKER", "D070 per-Picker service mode")
    require(sla_auto, "FIRST_REPORT", "D070 first-report service mode")
    # D108: dense numeric Picker shortage entry, stable selection, status backgrounds and per-user display scale.
    require(picker_layout, 'android:digits="0123456789"', "D108 numeric SKU input")
    require(picker_layout, 'android:completionThreshold="3"', "D108 three-digit suggestion threshold")
    require(picker_layout, 'android:hint="Nhập tối thiểu 3 chữ số SKU"', "D108 SKU hint")
    require(picker_layout, 'android:text="Xác nhận"', "D108 compact confirm action")
    require(picker_layout, 'android:text="Danh sách SKU đã báo hết hàng"', "D108 report history title")
    forbid(picker_layout, "Quét hoặc nhập SKU", "D108 removed redundant SKU label")
    forbid(picker_layout, "SKU tôi đã báo", "D108 removed old history title")
    require(picker, "selected?.sku == value", "D108 selected SKU suggestion suppression")
    require(picker, "autoInput?.dismissDropDown()", "D108 dropdown dismissal after selection")
    require(picker, "kit.rounded(kit.blueSoft, kit.blue, 9)", "D108 selected SKU emphasis")
    require(picker, "object : BaseAdapter()", "D108 status-card history adapter")
    require(picker, "kit.stockFill", "D108 has-stock light green")
    require(picker, "kit.pendingFill", "D108 pending light yellow")
    require(picker, "kit.skipFill", "D108 skip light red")
    require(picker, "kit.graySoft", "D108 withdrawn light grey")
    forbid(picker, "Mốc tự động:", "D108 no Picker automatic deadline time copy")
    forbid(picker, '"Tự động:"', "D108 no Picker automatic deadline label")
    require(main_layout, '@+id/btnTextMinus', "D108 Picker minus display control")
    require(main_layout, '@+id/btnTextPlus', "D108 Picker plus display control")
    require(main_layout, '@+id/btnTextReset', "D113 100 percent display reset control")
    require(main_activity, 'reset.setOnClickListener { applyScale(1.0f) }', "D113 quick 100 percent reset")
    require(picker_layout, 'android:visibility="gone"', "D113 empty selected-SKU card hidden")
    forbid(picker, '"Chưa chọn SKU"', "D113 remove empty selected-SKU copy")
    require(picker_layout, 'android:autoSizeMinTextSize="9sp"', "D113 confirm button scale fit")
    require(main_activity, '"INVALID_CREDENTIALS" -> "Tài khoản hoặc mật khẩu không đúng."', "D113 friendly login error")
    require(main_activity, 'btnTextReset', "D113 scale reset binding")
    require(inventory_api, "resolvedByDisplayName", "D113 Reporter resolver identity projection")
    require(reporter, 'Invent phản hồi lúc: $responseTime" + if (responder.isBlank()) "" else " bởi $responder"', "D113 Reporter responder copy")
    require(relay_agent, '"Chuyển xuống nền"', "D113 Agent background action")
    require(main_activity, 'getSharedPreferences("picker_display_scale_v1"', "D108 per-user scale persistence")
    require(main_activity, '"user:${session.userId}"', "D108 per-user scale key")
    require(main_activity, "coerceIn(0.8f, 1.4f)", "D108 bounded display scale")
    require(picker, "applyDisplayScale(root)", "D108 Picker text/input scale application")
    # D109: compact header, adjacent size controls, stationary bottom tabs and time-only history.
    require(main_layout, 'android:minHeight="56dp"', "D109 compact header minimum")
    require(main_layout, 'android:autoSizeTextType="uniform"', "D109 bounded header auto-size")
    minus_index = main_layout.find('@+id/btnTextMinus')
    plus_index = main_layout.find('@+id/btnTextPlus')
    log_index = main_layout.find('@+id/btnLog')
    if not (0 <= minus_index < plus_index < log_index):
        fail("D109 display controls must be ordered A−, A+, then Log")
    require(picker_layout, '@drawable/bg_picker_tab_selected', "D109 selected bottom tab surface")
    require(picker_layout, '@drawable/bg_picker_tab_idle', "D109 idle bottom tab surface")
    require(picker_layout, 'android:text="Báo hết hàng"', "D109 shortage tab label")
    require(picker_layout, 'android:text="Xác nhận đơn"', "D109 confirmation tab label")
    require(manifest, 'android:windowSoftInputMode="adjustResize"', "D118 keyboard-safe stationary tabs during IME")
    require(picker, 'DateTimeFormatter.ofPattern("HH:mm")', "D109 time-only formatter")
    require(picker, 'Báo hết lúc: ${timeOnly(row.reportedAt)}', "D109 reported time label")
    require(picker, '"Invent phản hồi lúc: ${timeOnly(row.resolvedAt)}"', "D109 Invent response time label")
    forbid(picker, 'DateTimeFormatter.ofPattern("dd/MM/yyyy")', "D109 no shortage-history date formatter")
    require(picker, "R.drawable.bg_picker_tab_selected", "D109 tab selected runtime styling")
    require(picker, "R.drawable.bg_picker_tab_idle", "D109 tab idle runtime styling")

    # D111: Reporter scale/confirmation cleanup and Android today-plus-unresolved projection.
    require(main_activity, 'getSharedPreferences("reporter_display_scale_v1"', "D111 per-user Reporter scale persistence")
    require(main_activity, "reporterDisplayScale(session)", "D111 Reporter scale restore")
    require(reporter, "applyDisplayScale(root)", "D111 Reporter display scale application")
    require(reporter, "private fun confirmResolution", "D111 Reporter pre-resolution confirmation")
    require(reporter, '.setPositiveButton("Xác nhận")', "D111 Reporter explicit confirmation action")
    require(reporter, "confirmingBatchIds", "D111 Reporter confirmation double-tap lock")
    require(reporter, '"Báo lúc: $reportTime', "D111 Reporter report time")
    require(reporter, 'Invent phản hồi lúc: $responseTime', "D111 Reporter response time")
    forbid(reporter, "Picker đã xác nhận", "D111 remove redundant Picker acknowledgement count")
    forbid(reporter, "Không có SKU đang xử lý.", "D111 remove redundant Reporter summary")
    require(inventory_api, "scope=APP_TODAY_OPEN", "D111 Android scoped history request")
    require(operational, 'APP_TODAY_OPEN_SCOPE = "APP_TODAY_OPEN"', "D111 service scoped history projection")
    require(operational, "t.reported_at >= ? OR (t.status = 'OPEN'", "D111 Picker today plus older unresolved SQL")
    require(operational, "b.first_report_at >= ?", "D111 Reporter resolved-today SQL")
    require(picker, "reportDate(it.reportedAt) == today || isUnresolved(it)", "D111 Picker defensive day/open filter")

    require(launcher, "onOpenResults", "distinct results route")
    require(main_activity, 'initialFilter = "HAS_STOCK"', "results initial filter")
    require(web, "sectionFromHash()", "Web hash route parser")
    require(web, "resolveInitialSection", "Web direct-route resolver")
    require(web, "canAccessSection", "Web route RBAC")

    print("ANDROID_OPERATIONAL_REGRESSION_PASS")


if __name__ == "__main__":
    main()
